import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Menu from "./components/menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-primary text-white p-4">
          <div className="container mx-auto flex justify-between items-center">
            <div className="text-2xl font-bold">
              <Link href="/">Home</Link>
            </div>
            <Menu />
            <nav className="hidden md:flex space-x-6">
              <Link href="/contacts">Contacts</Link>
              <Link href="/contacts">About us</Link>
              <Link href="/contacts">Learn more</Link>
            </nav>
          </div>
          <div
            id="mobile-menu"
            className="peer-checked:block hidden bg-primary text-white p-4 md:hidden"
          >
            <nav>
              <ul className="space-y-4">
                <li>
                  <Link href="/contacts">Contacts</Link>
                </li>
                <li>
                  <Link href="/contacts">About us</Link>
                </li>
                <li>
                  <Link href="/contacts">Learn more</Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        {children}
        <footer className="bg-accent text-white text-center p-4 flex justify-center items-center w-full">
          <ul className="flex space-x-2">
            <li>
              <Link href="/products">Products</Link>
            </li>
            <li>
              <Link href="/contacts">Contacts</Link>
            </li>
            <li>
              <Link href="/contacts">Learn more</Link>
            </li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
